import { Vendor, GeoLocation } from '@/src/types';

export const LAXMI_TEXTILES_LOCATION: GeoLocation = {
  lat: 11.6643,
  lng: 78.1460,
  name: 'Laxmi Textiles Main Store',
  address: '42 Main Bazaar Road, Salem Textile Hub, Tamil Nadu 636001',
};

export const VENDORS_CATALOG: Vendor[] = [
  {
    id: 'ven-kanchipuram',
    name: 'Kanchipuram Master Weavers',
    city: 'Kanchipuram',
    state: 'Tamil Nadu',
    specialty: 'Pure Mulberry Silk & Wedding Zari Sarees',
    rating: 4.9,
    phone: '+91 94432 10982',
    coordinates: { lat: 12.8342, lng: 79.7036 },
    catalog: [
      {
        id: 'vitem-kpm-silk-01',
        name: 'Kanchipuram Silk Saree – Crimson Gold',
        category: 'Sarees',
        fabric: 'Pure Mulberry Silk with Heavy Zari',
        color: 'Crimson Red & Rich Gold',
        unitPrice: 4200,
        retailEstimate: 7999,
        minimumOrderQty: 5,
        inStockAtMill: 45,
        description: 'Authentic 6.3m pure silk bridal saree woven on traditional handlooms.',
        defaultRack: 'Rack S-1 (Wedding Silk VIP Section)',
      },
      {
        id: 'vitem-kpm-temple-02',
        name: 'Temple Border Kanchi Pattu – Peacock Blue',
        category: 'Sarees',
        fabric: 'Pure Silk with Gold Korvai Border',
        color: 'Peacock Blue & Maroon',
        unitPrice: 3800,
        retailEstimate: 6899,
        minimumOrderQty: 5,
        inStockAtMill: 60,
        description: 'Traditional temple korvai border saree for festive occasions.',
        defaultRack: 'Rack S-1 (Wedding Silk VIP Section)',
      },
      {
        id: 'vitem-kpm-soft-03',
        name: 'Soft Silk Lightweight Saree – Pastel Green',
        category: 'Sarees',
        fabric: 'Soft Silk',
        color: 'Mint Green & Silver Zari',
        unitPrice: 2400,
        retailEstimate: 4500,
        minimumOrderQty: 10,
        inStockAtMill: 80,
        description: 'Lightweight easy-drape soft silk saree with modern silver motifs.',
        defaultRack: 'Rack S-2 (Soft Silks)',
      },
    ],
  },
  {
    id: 'ven-coimbatore',
    name: 'Coimbatore Cotton Mills',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    specialty: '100% Combed Pure Cotton & Daily Wear Sarees',
    rating: 4.8,
    phone: '+91 98422 45120',
    coordinates: { lat: 11.0168, lng: 76.9558 },
    catalog: [
      {
        id: 'vitem-cbe-cot-01',
        name: 'Cotton Saree – Royal Blue',
        category: 'Sarees',
        fabric: '100% Combed Pure Cotton',
        color: 'Royal Blue with Temple Border',
        unitPrice: 450,
        retailEstimate: 799,
        minimumOrderQty: 15,
        inStockAtMill: 150,
        description: 'High-demand breathable handloom cotton saree. Best seller for village customers.',
        defaultRack: 'Rack A-2 (Cotton Sarees)',
      },
      {
        id: 'vitem-cbe-printed-02',
        name: 'Daily Wear Cotton Saree – Floral Maroon',
        category: 'Sarees',
        fabric: '80s Count Pure Cotton',
        color: 'Deep Maroon Floral',
        unitPrice: 320,
        retailEstimate: 599,
        minimumOrderQty: 20,
        inStockAtMill: 200,
        description: 'Soft cotton daily wear saree, fast moving for working women.',
        defaultRack: 'Rack A-4 (Daily Cotton)',
      },
      {
        id: 'vitem-cbe-dhoti-03',
        name: 'Coimbatore Handloom Cotton Dhoti (Single)',
        category: 'Dhotis & Traditional',
        fabric: '100% Cotton with Gold Border',
        color: 'Pure White & Gold',
        unitPrice: 240,
        retailEstimate: 450,
        minimumOrderQty: 25,
        inStockAtMill: 120,
        description: 'Comfortable everyday cotton dhoti with border.',
        defaultRack: 'Rack D-1 (Dhoti Section)',
      },
    ],
  },
  {
    id: 'ven-salem',
    name: 'Salem Handlooms Syndicate',
    city: 'Salem',
    state: 'Tamil Nadu',
    specialty: 'Traditional Gold Zari Pattu Dhotis & Wedding Sets',
    rating: 4.9,
    phone: '+91 94421 88302',
    coordinates: { lat: 11.6643, lng: 78.1460 },
    catalog: [
      {
        id: 'vitem-slm-dho-01',
        name: 'Traditional Gold Zari Pattu Dhoti (Double)',
        category: 'Dhotis & Traditional',
        fabric: 'Pure Cotton Silk Blend (8 Muzham)',
        color: 'Cream with Kasavu Gold Border',
        unitPrice: 550,
        retailEstimate: 1100,
        minimumOrderQty: 10,
        inStockAtMill: 70,
        description: 'Essential festival and wedding dhoti set. Highest demand during muhurtham seasons.',
        defaultRack: 'Rack D-1 (Dhoti Section)',
      },
      {
        id: 'vitem-slm-ang-02',
        name: 'Wedding Dhoti & Angavastram Set',
        category: 'Dhotis & Traditional',
        fabric: 'Silk Cotton with 2-inch Gold Border',
        color: 'Ivory & Gold',
        unitPrice: 750,
        retailEstimate: 1499,
        minimumOrderQty: 10,
        inStockAtMill: 90,
        description: 'Groom wedding dhoti set with matching shoulder angavastram.',
        defaultRack: 'Rack D-1 (Dhoti Section)',
      },
    ],
  },
  {
    id: 'ven-tirupur',
    name: 'Tirupur Garments Hub',
    city: 'Tirupur',
    state: 'Tamil Nadu',
    specialty: "Men's Formal Shirts, Pure Linen & Festive Kurtas",
    rating: 4.7,
    phone: '+91 98430 67219',
    coordinates: { lat: 11.1085, lng: 77.3411 },
    catalog: [
      {
        id: 'vitem-tpr-sht-01',
        name: "Men's Cotton Formal Shirt – Sky Blue",
        category: "Men's Wear",
        fabric: 'Cotton Twill (Wrinkle-Resistant)',
        color: 'Sky Blue (Size 40)',
        unitPrice: 350,
        retailEstimate: 699,
        minimumOrderQty: 20,
        inStockAtMill: 180,
        description: 'Everyday office formal shirt with reinforced seams.',
        defaultRack: 'Rack M-3 (Men Formal Shirts)',
      },
      {
        id: 'vitem-tpr-kur-02',
        name: "Men's Pure Linen Kurta – Natural Cream",
        category: "Men's Wear",
        fabric: '100% Organic Linen',
        color: 'Cream (Size 42)',
        unitPrice: 750,
        retailEstimate: 1499,
        minimumOrderQty: 10,
        inStockAtMill: 50,
        description: 'Breathable festival kurta with wood-finish buttons.',
        defaultRack: 'Rack M-1 (Men Ethnic & Kurtas)',
      },
      {
        id: 'vitem-tpr-wht-03',
        name: "Men's Crisp White Festive Shirt",
        category: "Men's Wear",
        fabric: '100% Giza Cotton',
        color: 'Crisp White (Size 38/40/42)',
        unitPrice: 420,
        retailEstimate: 850,
        minimumOrderQty: 15,
        inStockAtMill: 110,
        description: 'Popular wedding & temple visit white shirt.',
        defaultRack: 'Rack M-3 (Men Formal Shirts)',
      },
    ],
  },
  {
    id: 'ven-erode',
    name: 'Erode Textile Processors',
    city: 'Erode',
    state: 'Tamil Nadu',
    specialty: 'School Uniform Sets, Poly-Cotton Cloth & Dress Materials',
    rating: 4.8,
    phone: '+91 98427 34812',
    coordinates: { lat: 11.3410, lng: 77.7172 },
    catalog: [
      {
        id: 'vitem-erd-uni-01',
        name: 'School Uniform Set – Navy & White',
        category: 'School Uniforms',
        fabric: 'Heavy Duty Poly-Cotton (Fade-Resistant)',
        color: 'Navy Blue & White (Size 32)',
        unitPrice: 280,
        retailEstimate: 550,
        minimumOrderQty: 25,
        inStockAtMill: 300,
        description: 'Official district standard school uniform bundle.',
        defaultRack: 'Rack U-2 (School Uniforms)',
      },
      {
        id: 'vitem-erd-khi-02',
        name: 'Khaki School / Industrial Uniform Cloth Roll',
        category: 'School Uniforms',
        fabric: 'Durable Drill Cotton',
        color: 'Standard Khaki',
        unitPrice: 220,
        retailEstimate: 450,
        minimumOrderQty: 20,
        inStockAtMill: 140,
        description: 'Heavy duty khaki drill uniform fabric.',
        defaultRack: 'Rack U-2 (School Uniforms)',
      },
    ],
  },
  {
    id: 'ven-surat',
    name: 'Surat Silk Mills',
    city: 'Surat',
    state: 'Gujarat',
    specialty: "Women's Chudidar Suits, Embroidered Materials & Georgettes",
    rating: 4.7,
    phone: '+91 98251 90234',
    coordinates: { lat: 21.1702, lng: 72.8311 },
    catalog: [
      {
        id: 'vitem-srt-chu-01',
        name: "Women's Chudidar Material – Deep Maroon",
        category: "Women's Wear",
        fabric: 'Chanderi Silk Cotton 3-Piece Set',
        color: 'Maroon & Gold Embroidery',
        unitPrice: 600,
        retailEstimate: 1199,
        minimumOrderQty: 10,
        inStockAtMill: 95,
        description: 'Unstitched suit with embroidered dupatta, top, and bottom.',
        defaultRack: 'Rack W-1 (Dress Materials & Chudidar)',
      },
      {
        id: 'vitem-srt-geo-02',
        name: 'Designer Georgette Printed Saree – Navy Floral',
        category: 'Sarees',
        fabric: 'Soft Georgette',
        color: 'Navy & Gold Foil Print',
        unitPrice: 520,
        retailEstimate: 999,
        minimumOrderQty: 15,
        inStockAtMill: 120,
        description: 'Lightweight designer partywear georgette saree.',
        defaultRack: 'Rack S-4 (Banarasi & Heavy Silks)',
      },
    ],
  },
  {
    id: 'ven-madurai',
    name: 'Madurai Weavers Syndicate',
    city: 'Madurai',
    state: 'Tamil Nadu',
    specialty: 'Madurai Sungudi Sarees & Traditional Kids Pattu Pavadai',
    rating: 4.9,
    phone: '+91 94433 71209',
    coordinates: { lat: 9.9252, lng: 78.1198 },
    catalog: [
      {
        id: 'vitem-mdu-sun-01',
        name: 'Daily Wear Sungudi Cotton Saree – Mustard',
        category: 'Sarees',
        fabric: 'Madurai Sungudi Cotton (Tie & Dye)',
        color: 'Mustard Yellow & Dot Prints',
        unitPrice: 220,
        retailEstimate: 450,
        minimumOrderQty: 20,
        inStockAtMill: 160,
        description: 'Authentic Madurai Sungudi tie-and-dye cotton saree with zari border.',
        defaultRack: 'Rack A-4 (Daily Cotton)',
      },
      {
        id: 'vitem-mdu-kid-02',
        name: 'Kids Pattu Pavadai – Peacock Blue & Pink',
        category: 'Kids Wear',
        fabric: 'Art Silk with Gold Zari',
        color: 'Peacock Blue & Magenta (Size 26)',
        unitPrice: 650,
        retailEstimate: 1250,
        minimumOrderQty: 10,
        inStockAtMill: 65,
        description: 'Festival favorite ethnic wear for young girls.',
        defaultRack: 'Rack K-2 (Kids Festival Wear)',
      },
    ],
  },
];
